// Configuração Tailwind compartilhada entre todas as telas do painel admin
// Inclua este bloco como <script id="tailwind-config"> em cada tela

const IGNITE_TAILWIND_CONFIG = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#5a4136",
        "on-primary": "#561f00",
        "surface-variant": "#353534",
        "tertiary-container": "#af947c",
        "surface-container": "#201f1f",
        "secondary-container": "#ea6b1e",
        "error-container": "#93000a",
        "on-secondary-fixed": "#351000",
        "tertiary": "#dfc1a8",
        "on-background": "#e5e2e1",
        "primary-container": "#ff6b00",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#562000",
        "surface": "#131313",
        "surface-container-high": "#2a2a2a",
        "outline": "#a98a7d",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#572000",
        "background": "#131313",
        "on-error": "#690005",
        "primary": "#ffb693",
        "on-surface-variant": "#e2bfb0",
        "secondary": "#ffb693",
        "surface-container-low": "#1c1b1b",
        "surface-bright": "#3a3939",
        "error": "#ffb4ab",
        "on-tertiary": "#3f2d1b",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#ffdbcc",
        "on-secondary-container": "#4b1b00",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "success": "#4caf88",
        "success-container": "#1a3d2e",
        "on-success": "#0d2a1e",
        "warning": "#f5c842",
        "warning-container": "#3d3010",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
};
